(chore) Cleaner install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,16 +1,7 @@
 #!/usr/bin/env bash
 
-# Exit codes. Ref -> https://www.cyberciti.biz/faq/linux-bash-exit-status-set-exit-statusin-bash/
-EC_SUCCEESS=0
-EC_FAILURE=1
-EC_FILE_EXISTS=17
-EC_NOT_IMPLEMENTED=38
-EC_PACKAGE_NOT_INSTALLED=65
-
-set -e
-
 setup_colors() {
-  if [[ -t 2 ]] && [[ $NO_COLOR == 1 ]] && [[ "${TERM-}" != "dumb" ]]; then
+  if [[ -t 2 ]] && [[ "${TERM-}" != "dumb" ]]; then
     # Color codes
     RED='\033[1;31m'
     YELLOW='\033[1;33m'
@@ -35,37 +26,6 @@ setup_colors() {
   fi
 }
 
-show_usage() {
-  local exit_code=${1:-$EC_SUCCEESS}
-
-  printf "%b\n" "$(
-    cat <<EOF
-USAGE:
-  <install-cmd> <flags>
-
-DESCRIPTION:
-  Simple install command for \"dot\" script
-
-FLAGS:
-  --help, -h            Print this help message and exit
-  --install-deps, -i    Install missing dependencies without prompting
-  --upgrade, -u         Re-write the \"dot\" script if exists without prompting
-  --verbose             Show more stuff in case of an error (set -x)
-  --no-color, -n        Run script without colors or emojis
-EOF
-  )"
-
-  exit $exit_code
-}
-
-abort() {
-  local msg="$1"
-  local exit_code="${2:-$EC_FAILURE}"
-
-  printf "${RED}%s\n${NC}" "$msg" >&2
-  exit $exit_code
-}
-
 exists() {
   local testing_command="$1"
 
@@ -76,127 +36,115 @@ exists() {
   fi
 }
 
-ask_confirmation() {
-  local prompt="$1"
-  local action="$2"
-  local failure_exit_code="${3:-$EC_FAILURE}"
+clone_repo() {
+  echo "Cloning repo..."
+  git clone https://github.com/epicmet/.dotfiles "$HOME/.dotfiles"
+}
 
-  #local deny_msg="${4:-Please resolve the issue and retry again.}"
-  local deny_msg="Confirmation denied! Please resolve the issue and retry again."
-  # local accept_msg="${5:-}"
-  local accept_msg="Doing the thing!"
+install_deps_arch() {
+  echo "Installing arch deps..."
 
+  if [[ $(exists pacman) == 1 ]]; then
+    echo -e "${RED} Could not find pacman in your \$PATH!${NC}"
+    exit 1
+  fi
+
+  sudo pacman -Sy
+
+  sudo pacman -S \
+    git \
+    base-devel \
+    curl \
+    openssl \
+    gum \
+    neovim \
+    tmux \
+    tree-sitter \
+    zsh \
+    lua \
+    luarocks \
+    stow \
+    fzf \
+    starship \
+    fd \
+    ripgrep \
+    jq \
+    zoxide \
+    bat \
+    dua-cli \
+    bpytop \
+    ttf-dejavu \
+    ttf-cascadia-mono-nerd \
+    rbw \
+    docker \
+    ansible-core \
+    lazygit \
+    wezterm \
+    eza \
+    i3-wm
+
+  mkdir -p "$HOME/Software"
+  git clone https://aur.archlinux.org/yay.git "$HOME/Software"
+  pushd "$HOME/Software/yay"
+  makepkg -si
+
+  echo "Installing AURs ..."
+  yay -S \
+    lazydocker \
+    nvm \
+    brave-bin \
+    tmux-plugin-manager \
+    yq
+
+  popd
+}
+
+install_deps_mac() {
+  # TODO: Figure something out for MacOS
+  echo "MacOS DEPS NOT IMPLEMENTED!"
+  exit 1
+}
+
+install_deps() {
   while true; do
-    read -p "$prompt (y/n) " choice
-    case "$choice" in
-    y | Y)
-      # echo -e $accept_msg
-      $action
+    local prompt="Choose OS (1: archliux, 2: MacOS): "
+    read -p "$prompt" choice
+
+    case $choice in
+    '1')
+      install_deps_arch
       break
       ;;
-    n | N)
-      abort "$deny_msg" "$failure_exit_code"
+    '2')
+      install_deps_mac
+      break
       ;;
     *)
-      echo -e "Invalid choice \"$choice\", pass \"y\" or \"n\" to accept or deny confirmation"
+      echo "invalid choice!"
       echo
       ;;
     esac
   done
 }
 
-ensure_install() {
-  local pkg="$1"
-  local install_pkg_func="$2"
+main() {
+  setup_colors
 
-  echo -e "${ARROW} Ensure installing ${pkg}"
-
-  if [[ ! $(exists $pkg) == 0 ]]; then
-    echo -e "${WARNING} Could not find \"${pkg}\" in your PATH"
-    if [[ $INSTALL_DEPS_NO_PROMPT == 0 ]]; then
-      $install_pkg_func
-    else
-      ask_confirmation "Do you want to install ${pkg}?" $install_pkg_func $EC_PACKAGE_NOT_INSTALLED
-    fi
+  if [[ $(exists dot) == 0 ]]; then
+    echo -e "${RED} There is already a \'dot\' executable found in your \$PATH!${NC}"
+    exit 1
   fi
+
+  install_deps
+
+  clone_repo
+
+  pushd "$HOME/.dotfiles"
+  dot sync
+  dot init
+  popd
 }
 
-install_dot() {
-  curl -fsSL https://raw.githubusercontent.com/MahdiAghaei1/.dotfiles/master/dot >temp_dot_executable
+main
 
-  # If the Unique ID is 0, the user has root privileges
-  if [ ! "$UID" -eq 0 ]; then
-    sudo -p "[Need sudo for installing dot in your path] Password: " mv temp_dot_executable /usr/local/bin/dot &&
-      sudo chmod +x /usr/local/bin/dot
-  fi
-}
-
-# TODO : Install brew and others in one go.
-install_brew() {
-  echo -e "${WARNING} We can't install brew and other dependencies in one go. Install brew with the command below, reload you terminal session and run the script again."
-
-  echo
-  echo 'bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
-
-  exit $EC_PACKAGE_NOT_INSTALLED
-}
-
-install_gum() {
-  echo "Installing gum..."
-  brew install gum
-}
-
-install_ansible() {
-  echo "Installing ansible..."
-  brew install ansible
-}
-
-INSTALL_DEPS_NO_PROMPT=1
-UPGRADE_DOT_SCRIPT_NO_PROMPT=1
-NO_COLOR=1
-
-for arg in "$@"; do
-  case $arg in
-  --verbose)
-    set -x
-    ;;
-  -h | --help)
-    show_usage $EC_SUCCEESS
-    ;;
-  -i | --install-deps)
-    INSTALL_DEPS_NO_PROMPT=0
-    ;;
-  -u | --upgrade)
-    UPGRADE_DOT_SCRIPT_NO_PROMPT=0
-    ;;
-  -n | --no-color)
-    NO_COLOR=0
-    ;;
-  *)
-    abort "Unkown flag $arg"
-    ;;
-
-  esac
-done
-
-setup_colors
-
-ensure_install brew install_brew
-ensure_install gum install_gum
-ensure_install ansible install_ansible
-
-if [[ $(exists dot) == 0 ]]; then
-  echo -e "${WARNING} There is already a \'dot\' executable found in your \$PATH"
-  if [[ $UPGRADE_DOT_SCRIPT_NO_PROMPT == 0 ]]; then
-    echo "Updating dot..."
-    install_dot
-  else
-    ask_confirmation "Do you want to re-write/upgrade it?" install_dot $EC_FILE_EXISTS
-  fi
-else
-  install_dot
-fi
-
-echo -e "Success! Now run \`dot init\` (You may need to reload your terminal session)"
-
-exit $EC_SUCCEESS
+exit 0
